---
# tasks file for nagiosxi_install
#- name: Register and subscribe Red Hat
 # include_tasks: register_redhat.yml

#- name: Install prerequisites
 # include_tasks: prerequisites.yml

- name: Install Nagios XI
  include_tasks: install_nagiosxi.yml