---
  
    - name: Register with Red Hat and auto-subscribe to content
      community.general.redhat_subscription:
        state: present
        username: "{{ redhat_username }}"
        password: "{{ redhat_password }}"
        auto_attach: true
      #when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"
      #register: redhat_register
  
    - name: Enable repository management
      ansible.builtin.command: subscription-manager config --rhsm.manage_repos=1
      #when: redhat_register.changed